// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: serialization.proto

package logstrata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_PUT       Command = 0
	Command_DELETE    Command = 1
	Command_WRITE_SST Command = 2
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
		2: "WRITE_SST",
	}
	Command_value = map[string]int32{
		"PUT":       0,
		"DELETE":    1,
		"WRITE_SST": 2,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_serialization_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_serialization_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{0}
}

type LSMEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Command       Command                `protobuf:"varint,2,opt,name=command,proto3,enum=grpcapi.Command" json:"command,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSMEntry) Reset() {
	*x = LSMEntry{}
	mi := &file_serialization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSMEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSMEntry) ProtoMessage() {}

func (x *LSMEntry) ProtoReflect() protoreflect.Message {
	mi := &file_serialization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSMEntry.ProtoReflect.Descriptor instead.
func (*LSMEntry) Descriptor() ([]byte, []int) {
	return file_serialization_proto_rawDescGZIP(), []int{0}
}

func (x *LSMEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LSMEntry) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_PUT
}

func (x *LSMEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LSMEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_serialization_proto protoreflect.FileDescriptor

const file_serialization_proto_rawDesc = "" +
	"\n" +
	"\x13serialization.proto\x12\agrpcapi\"\x8b\x01\n" +
	"\bLSMEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\acommand\x18\x02 \x01(\x0e2\x10.grpcapi.CommandR\acommand\x12\x19\n" +
	"\x05value\x18\x03 \x01(\fH\x00R\x05value\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampB\b\n" +
	"\x06_value*-\n" +
	"\aCommand\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\r\n" +
	"\tWRITE_SST\x10\x02B!Z\x1fgithub.com/beansntato/logstratab\x06proto3"

var (
	file_serialization_proto_rawDescOnce sync.Once
	file_serialization_proto_rawDescData []byte
)

func file_serialization_proto_rawDescGZIP() []byte {
	file_serialization_proto_rawDescOnce.Do(func() {
		file_serialization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serialization_proto_rawDesc), len(file_serialization_proto_rawDesc)))
	})
	return file_serialization_proto_rawDescData
}

var file_serialization_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_serialization_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_serialization_proto_goTypes = []any{
	(Command)(0),     // 0: grpcapi.Command
	(*LSMEntry)(nil), // 1: grpcapi.LSMEntry
}
var file_serialization_proto_depIdxs = []int32{
	0, // 0: grpcapi.LSMEntry.command:type_name -> grpcapi.Command
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_serialization_proto_init() }
func file_serialization_proto_init() {
	if File_serialization_proto != nil {
		return
	}
	file_serialization_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serialization_proto_rawDesc), len(file_serialization_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serialization_proto_goTypes,
		DependencyIndexes: file_serialization_proto_depIdxs,
		EnumInfos:         file_serialization_proto_enumTypes,
		MessageInfos:      file_serialization_proto_msgTypes,
	}.Build()
	File_serialization_proto = out.File
	file_serialization_proto_goTypes = nil
	file_serialization_proto_depIdxs = nil
}
